
HAI 1.2 BTW some text


I HAS A ANIMAL 
VISIBLE "WHAT IZ YR ANIMAL"
GIMMEH ANIMAL
BOTH SAEM ANIMAL AN "CAT"
O RLY?
  YA RLY, VISIBLE "J00 HAV A CAT"
  MEBBE BOTH SAEM ANIMAL AN "MAUS"
    VISIBLE "NOM NOM NOM. I EATED IT."
  MEBBE BOTH SAEM ANIMAL AN "DOLPHIN"
    VISIBLE "J00 R GREAT"
NO WAI, VISIBLE "J00 SUX"

OIC
KTHXBYE